
JAVAFLAGS=-Xmx128m -Xss128m

build: 
	javac *.java

run-p1:
	java ${JAVAFLAGS} P1
run-p2:
	java ${JAVAFLAGS} P2
run-p3:
	java ${JAVA_FLAGS} P3
run-p4:
	java ${JAVA_FLAGS} Bonus

clean:
	rm -f *.class
